### ISSUE TITLE
Перенести файлы

### ISSUE THREAD

**Issue by seemann9** [sicamp/sicamp.github.io#23]
CDN Github'а опять заблокирован некоторыми провайдерами, а с ним ссылки с сайта на файлы типа договора.

**Comment by isqua** [comment]
Уот говно.

**Comment by seemann9** [comment]
http://school9.perm.ru/camp/files/dogovor.doc
http://school9.perm.ru/camp/files/soglasie.docx

**Comment by isqua** [comment]
deployed
