### ISSUE TITLE
Релиз 2017

### ISSUE THREAD

**Issue by seemann9** [sicamp/sicamp.github.io#31]
- [x] Оставить только страницы: index, letsgo, entrance (things и enlisted пока не нужны).

- [ ] На главной нужно будет исправить стоимость, площадку и даты, но я пока не могу сказать на что.

## letsgo

- [x] Вернуть, как было в том году изначально (в смысле без реквизитов, заезда и т.д.)
тип так: https://web.archive.org/web/20160506070354/http://sicamp.ru/letsgo
- [x] Видимо добавится пункт "зарегистрироваться в системе" или типа того, и со ссылками на анкеты что-то произойдет.
- [x] Опять же, даты и стоимость как-то изменятся.

## entrance #34 

- [x] В текст про вступительную добавить фразу про самостоятельное выполнение работы.
- [x] В описаниях параллелей разделить "что требуется", "что будем изучать".
- [x] Добавить к каждой параллели под спойлер подробный план (с дисклеймером, что это темы, изучавшиеся в том году, и в этом могут несколько измениться). Список тем - https://docs.google.com/document/d/1Ov_tjHT1RaSEJfbhPgfmacOxp66BsHa4wlzIsIZp4A0/edit?usp=sharing
- [x] Из описания параллели C убрать слова "вычислительная геометрия".
- [x] В описаниях параллелей C и B "heap" заменить на "куча".
- [x] Добавить параллель A', описание:

"Алгоритмы и структуры данных++
Параллель ориентирована на тех, кто уже в некоторой степени знаком с материалом параллели B, но ещё не имеет достаточного опыта для параллели A. Подразумевается знакомство со структурами данных (дерево отрезков), алгоритмами на строках (хеширование, Z/префикс-функция), алгоритмами на графах, в том числе поиска пути минимального веса и остова минимального веса во взвешенных графах. Изучаться будут более продвинутые темы параллели B и некоторые алгоритмы из параллели A."

- [x] Добавить к тексту:
"Обратите внимание: у каждой параллели есть возрастные ограничения. Также нельзя поступать в ту параллель, в которой вы уже учились. Вас зачислят в ЛКЛ, если вы пройдёте по конкурсу хотя бы в одну из параллелей, в которую можете поступать. К сожалению, мы вынуждены отказать в зачислении тем, кто получил на зачёте в прошлом году оценку "2"."

- [x] Добавить к параллелям классы:
A 9-10
A' 9-10
B 8-10
B' 7-10
C 7-9
C' 6-8
D 6-7

- [x] Там где бонусы апнуть год.
- [x] Список освобожденных от вступительной:
https://docs.google.com/spreadsheets/d/1qN7t8T3knxFZ_1bTuCKJJialyRaUsqe1qH07txxVQOY/edit?usp=sharing
- [x] Добавить параллель P, описание позже.
- [ ] Обновить список задач.

**Comment by isqua** [comment]
> В описаниях параллелей разделить "что требуется", "что будем изучать".

Видимо нужны тексты. Ну например в параллели B' такое описание:

> Параллель ориентирована на школьников, которые уже знакомы с алгоритмами параллели C. В данной параллели особое внимание уделяется умению реализовать различные алгоритмы и применять их для решения задач.

Его так что ли делить ↓, это ок?

Что требуется | Что будем изучать
----|----
 Параллель ориентирована на школьников, которые уже знакомы с алгоритмами параллели C. | В данной параллели особое внимание уделяется умению реализовать различные алгоритмы и применять их для решения задач.

**Comment by seemann9** [comment]
Попробовал переписать эти тексты

Параллель | Что требуется | Что будем изучать
----|----|----
D | <ul><li>Умение проводить простейшие математические рассуждения</li><li>Знакомство с базовыми понятиями дискретной математики и понятием алгоритма</li><li>Умение программировать не требуется</li></ul>|<ul><li>Основные принципы написания программ, работа в среде разработки</li><li>Базовые типы данных и выражения языка программирования</li><li>Базовые алгоритмы теории чисел, комбинаторики, теории графов</li></ul>
C′ | <ul><li> Владение основами языка программирования: вводом-выводом, базовыми операторами и типами данных</li> <li> Небольшой опыт решения задач, умение самостоятельно доводить простейшие программы до рабочего состояния</li></ul> | <ul><li>Базовые алгоритмы теории чисел, комбинаторики, теории графов</li> <li>Базовые структуры данных</li><li>Алгоритмы сортировки, в том числе быстрой</li></ul>
C|<ul><li>Уверенное владение основами языка программирования</li><li>Опыт решения задач</li><li>Знание базовых алгоритмов комбинаторики и теории чисел</li></ul>|<ul><li>Базовые структуры данных</li><li>Техники бинарного поиска, динамического программирования, хеширования</li><li>Классические алгоритмы теории графов</li></ul>
B'|<ul><li>Уверенное владение основами языка программирования</li><li>Знание алгоритмов параллелей C' и C</li><li>Опыт решения задач</li></ul>|<ul><li>Применение и более глубокое изучение уже известных алгоритмов</li><li>Практика решения задач с использованием нетривиальных приёмов и алгоритмов</li></ul>
B|<ul><li>Уверенное владение языком программирования</li><li>Опыт решения задач с применением алгоритмов</li><li>Знание основных алгоритмов на графах, алгоритма быстрой сортировки, основных структур данных (стек, очередь, список, куча)</li><li>Уверенное владение техниками перебора, динамического программирования</li></ul>|<ul><li>Cтруктуры данных на основе деревьев</li><li>Алгоритмы на строках и графах</li><li>Продвинутые методы динамического программирования</li><li>Задачи вычислительной геометрии</li></ul>
A'|<ul><li>Опыт решения сложных задач и участия в олимпиадах</li><li>Знакомство с темами параллели B: деревом отрезков, строковыми алгоритмами, алгоритмами на графах</li></ul>|<ul><li>Примение алгоритмов и техник параллели B к решению задач</li><li>Продвинутые алгоритмы: игры на графах, паросочетания, динамическое программирование по профилю</li></ul>
A|<ul><li>Значительный опыт решения задач и участия в олимпиадах</li><li>Уверенное владение алгоритмами параллели B, в том числе структурами данных</li></ul>|<ul><li>Решение многоходовых задач с использованием сложных алгоритмов и структур данных</li><li>Продвинутые алгоритмы: потоки, игры на графах, LCA и центроидная декомпозиция дерева</li><li>Практика написания контестов на время</li></ul>

**Comment by seemann9** [comment]
Даты: 9-29 августа 2017
Место: Лагерь "Комета", село Янычи
Сайта у них нет, можно дать линк на какую-нибудь карту, координаты 57.6706779, 56.4064264 :)
