### ISSUE TITLE
Информация по документам и оплате

### ISSUE THREAD

**Issue by seemann9** [sicamp/sicamp.github.io#42]
## Оплата

* Теперь нет двух частей оплаты, вся сумма в одном договоре.

* "Отправьте безналичный перевод по реквизитам ООО «Элпис», указанным в договоре. Учтите, что банк может брать комиссию за перевод. После оплаты отправьте копию квитанции на gm_shulgina@mail.ru. Если вам нужен счёт, напишите на тот же адрес. В конце смены мы отдадим вам договор об оказании услуг и корешок путёвки." - здесь всё так, только ООО "Галактика" теперь.

* Оплатить нужно до 1-го августа.

* Пермские школьники вместо безнала могут отдать деньги ГМ, только нужно предварительно договориться.

* Для школьников из Екатеринбурга часть путёвки оплачивается компанией "СКБ Контур", подробная информация позже.

## Документы
* Договор, заполненный и подписанный родителями, в 2 экз., в каждом только один школьник - всё как раньше.
* Подписанное родителями приложение к договору - правила пребывания в лагере.
* Согласие на получение первичной медицинской помощи (нужно заполнить только первые три строчки).
* Медицинская справка 079у - всё как раньше.
* Копия полиса - всё как раньше.
* Инфекционная справка - всё как раньше.

Договор, приложение и согласие в архивчике [docs.zip](https://github.com/sicamp/sicamp.github.io/files/1072699/docs.zip).

**Comment by isqua** [comment]
А можно файлики залить на school9, где они в прошлый раз хостились?

**Comment by seemann9** [comment]
https://school9.perm.ru/camp/Dogovor_Kometa.doc
https://school9.perm.ru/camp/Prilozhenie_1_pravila.doc
https://school9.perm.ru/camp/Dobrovolnoe_soglasie.docx

**Comment by isqua** [comment]
А приложение в договоре — только в одном экземпляре?

**Comment by seemann9** [comment]
Можно только в одном.
