### ISSUE TITLE
Запилить список зачисленных

### ISSUE THREAD

**Issue by seemann9** [sicamp/sicamp.github.io#7]
Список зачисленных + мотивирующий абзац, формат видимо как на старом сайте

**Comment by isqua** [comment]
Чо за мотивирующий абзац?

**Comment by seemann9** [comment]
То что перед списком на http://school9.perm.ru/camp/list/.
Но это поздняя версия, ее надо подхачить немного.

**Comment by isqua** [comment]
Ок. А списки уже есть?

**Comment by seemann9** [comment]
Конечно нет :)
К понедельнику надеюсь что будут
