### ISSUE TITLE
Запилить страничку с документами и оплатой

### ISSUE THREAD

**Issue by seemann9** [sicamp/sicamp.github.io#8]

**Comment by isqua** [comment]
Реквизиты скинь.

**Comment by seemann9** [comment]
ООО «ЭЛПИС»
614000, г. Пермь, ул. Ленина, 64
Тел.: 8(342) 202-35-55
ИНН/КПП 5902166596/590201001
ОГРН 1085902010325
Р/С 40702810149490059752
В Западно-Уральский банк ПАО "Сбербанк" г. Пермь 
К/с 30101810900000000603 БИК 045773603
Назначение платежа: оплата услуг по договору №______
От «_____»_____________2016

**Comment by seemann9** [comment]
Отличия от http://school9.perm.ru/camp/documents/:

Документы:
* новый файл договора - в архиве
* пункт 3 "заявление на согласие провести медосмотр" не нужен
* зато появилось "согласие на обработку персональных данных", его нужно заполнить, есть в архиве
* справка - все так же

Оплата:
* изменились суммы: общая 32500, в лагерь - 25500, вторая часть - 7000
* дальше все так же, только реквизиты другие (и название лагеря :))
* про сертификат можно убрать стоимости и все, оставить только, что его нужно отдать ГМ


[docs.zip](https://github.com/sicamp/sicamp.github.io/files/303707/docs.zip)

**Comment by seemann9** [comment]
Проапдейченный договор
[doc.zip](https://github.com/sicamp/sicamp.github.io/files/304750/doc.zip)
"что при переводе через отделения Западно-Уральского банка Сбербанка России комиссия не удерживается." - и вот это тоже надо убрать

**Comment by isqua** [comment]
Значит из доков нужно:

 * 2 экземпляра договора;
 * согласие на обработку персональных данных;
 * копию полиса;
 * медицинскую справку.
